#!/bin/sh

progs="autoconf automake autopoint gettext libtoolize make pkg-config"

for p in ${progs}; do
	if test -z "$(${p} --version 2>/dev/null)"; then
		echo "Please install ${p}"
		result=1
	fi
done

[ -z ${result} ] || exit 1

mkdir -p m4
exec autoreconf --force --install ${@}
